AllCops:
  NewCops: enable
  DisplayCopNames: true
  TargetRubyVersion: 3.0
  Include:
    - '**/Gemfile'
    - '**/Rakefile'
    - '**/Appraisals'
  Exclude:
    - 'spec/dummy/**/*'
    - 'lib/generators/**/*'

Style/Encoding:
  Enabled: true

Metrics/LineLength:
  Max: 150

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
